// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdwL10mvoh3xe1Wv7MmQUGq9641T7dtHg',
    appId: '1:874170835924:web:29cec53f0e9e2809c92c41',
    messagingSenderId: '874170835924',
    projectId: 'sqlquanlynha',
    authDomain: 'sqlquanlynha.firebaseapp.com',
    storageBucket: 'sqlquanlynha.firebasestorage.app',
    measurementId: 'G-CYS9KLR892',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCct9Ko0xRxzyGJjET9WB82yX4vXSEfgL4',
    appId: '1:874170835924:android:7e5028037cd12f0ac92c41',
    messagingSenderId: '874170835924',
    projectId: 'sqlquanlynha',
    storageBucket: 'sqlquanlynha.firebasestorage.app',
  );
}
